// Emits ArchcarKit's Theme.swift from the desktop's *computed* design tokens.
//
// The desktop stylesheet resolves its final values through several override
// passes (neutral -> theme -> charcoal -> polish -> final) where import order is
// load-bearing, so reading declarations out of the source files gives the wrong
// answer. Loading the built bundle in a browser and asking for the computed
// value gives the right one.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { chromium } from "playwright";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");
const assets = join(repoRoot, "desktop", "dist", "assets");
const output = join(here, "..", "ArchcarKit", "Sources", "ArchcarKit", "Theme", "Theme.swift");

const cssFiles = readdirSync(assets).filter((name) => name.endsWith(".css"));
if (cssFiles.length === 0) {
  console.error("No built CSS found. Run `make desktop-build` first.");
  process.exit(1);
}
const css = cssFiles.map((name) => readFileSync(join(assets, name), "utf8")).join("\n");

// Every custom property the bundle declares, in sorted order for a stable diff.
const names = [...new Set([...css.matchAll(/(--[a-z0-9-]+)\s*:/gi)].map((m) => m[1]))].sort();

const browser = await chromium.launch();
const page = await browser.newPage();
await page.setContent("<!doctype html><html><body></body></html>");
await page.addStyleTag({ content: css });

// The desktop toggles `lc-theme-dark` / `lc-theme-light` on <body>, so the
// tokens are read there rather than on the document element.
async function read(themeClass) {
  return page.evaluate(
    ([names, themeClass]) => {
      document.body.className = themeClass;
      const style = getComputedStyle(document.body);

      // getComputedStyle hands back a custom property as *declared*, so a
      // token written as color-mix(...) or var(...) arrives unresolved and
      // useless to Swift. Assigning it to a real colour property forces the
      // engine to resolve it.
      //
      // The catch: a token that is not a colour at all — a duration, a radius,
      // a font stack — makes that declaration invalid at computed-value time,
      // and `color` then *inherits* rather than keeping the value it had. So
      // every token is probed twice against two different inherited colours;
      // one that tracks the parent did not resolve, and its declared value is
      // kept instead.
      const probe = document.createElement("div");
      const parent = document.createElement("div");
      parent.appendChild(probe);
      document.body.appendChild(parent);

      function resolvedColour(name, inherited) {
        parent.style.color = inherited;
        probe.style.color = "";
        probe.style.color = `var(${name})`;
        return getComputedStyle(probe).color;
      }

      const out = {};
      for (const name of names) {
        const declared = style.getPropertyValue(name).trim();
        if (!declared) continue;
        const first = resolvedColour(name, "rgb(1, 2, 3)");
        const second = resolvedColour(name, "rgb(4, 5, 6)");
        const isColour =
          first === second && first !== "rgb(1, 2, 3)" && second !== "rgb(4, 5, 6)";
        out[name] = isColour ? first : declared;
      }
      parent.remove();
      return out;
    },
    [names, themeClass],
  );
}

const dark = await read("lc-theme-dark");
const light = await read("lc-theme-light");
await browser.close();

// A token defined in only one tone renders as a hole on the other, so the two
// dictionaries are filled out to the same key set with the dark value as the
// fallback — the same thing the desktop does by cascading over its dark base.
for (const name of Object.keys(dark)) {
  if (!(name in light)) light[name] = dark[name];
}
for (const name of Object.keys(light)) {
  if (!(name in dark)) dark[name] = light[name];
}

const swiftDictionary = (tokens) =>
  Object.keys(tokens)
    .sort()
    .map((name) => `        ${JSON.stringify(name)}: ${JSON.stringify(tokens[name])},`)
    .join("\n");

writeFileSync(
  output,
  `// Generated by ios/tools/generate-theme.mjs. Do not edit by hand.
//
// Values are the *computed* custom properties from the built desktop CSS
// bundle, so the phone and the desktop resolve to the same colours even though
// the desktop's value only exists after several override passes.
import Foundation

public struct ColorComponents: Sendable, Equatable {
    public let red: Double
    public let green: Double
    public let blue: Double
    public let alpha: Double

    public init(red: Double, green: Double, blue: Double, alpha: Double) {
        self.red = red
        self.green = green
        self.blue = blue
        self.alpha = alpha
    }
}

public struct Palette: Sendable {
    public let tokens: [String: String]

    public init(tokens: [String: String]) { self.tokens = tokens }

    public func raw(_ name: String) -> String? { tokens[name] }

    public func color(_ name: String) -> ColorComponents? {
        guard let value = tokens[name] else { return nil }
        return ColorComponents(css: value)
    }
}

public enum Theme {
    public static let dark = Palette(tokens: [
${swiftDictionary(dark)}
    ])

    public static let light = Palette(tokens: [
${swiftDictionary(light)}
    ])
}
`,
  "utf8",
);

console.log(`Wrote ${Object.keys(dark).length} dark and ${Object.keys(light).length} light tokens.`);
