import { createSignal, createResource, Show, Switch, Match, For } from "solid-js";
import {
  actions,
  repositoriesStore
} from "@/store";
import {
  listGithubWork,
  send,
  type GithubWorkItem
} from "@/bridge/client";
import {  useSubmit,  relTime } from "./DialogShared";

// Global modal host. Renders the form for the active dialog spec. Every form
// calls into `actions.*`, which logs the action, sends the archcar request, and
// re-pulls the inventory on success.

// Create a workspace from a branch, prompt, GitHub issue/PR, or Linear issue.
export function CreateWorkspaceForm(props: { repository: string; onDone: () => void }) {
  // Two ways to start a workspace. Names + branches are always autogenerated
  // (linux/distro codenames) in core; the Prompt flow lets the agent rename via
  // <archductor_metadata> on the first message, the Github flow uses the
  // {prefix}/gh-{issue|pr}-{n} branch scheme.
  type Source = "prompt" | "branch" | "github" | "linear";
  const [source, setSource] = createSignal<Source>("prompt");
  const [prompt, setPrompt] = createSignal("");
  const [selected, setSelected] = createSignal<GithubWorkItem | null>(null);
  const [linearIssue, setLinearIssue] = createSignal("");
  const [filter, setFilter] = createSignal("");
  // Branch/base source (restores the GTK "create from branch/base" flow).
  const [wsName, setWsName] = createSignal("");
  const [wsBranch, setWsBranch] = createSignal("");
  const [wsBase, setWsBase] = createSignal("");
  // Available base branches, loaded when the Branch tab is opened.
  const [baseBranches] = createResource(
    () => (source() === "branch" ? props.repository : undefined),
    async (repository): Promise<string[]> => {
      try {
        const res = await send({ type: "list_repository_branches", repository });
        return res.type === "repository_branches" ? res.branches : [];
      } catch {
        return [];
      }
    },
  );

  const rootPath = () => repositoriesStore.row(props.repository)?.rootPath ?? "";

  // Lazily fetch open issues + PRs the first time the Github tab is opened.
  type WorkResult = { ok: true; items: GithubWorkItem[] } | { ok: false; error: string };
  const [work, { refetch: refetchWork }] = createResource<WorkResult, string>(
    () => (source() === "github" && rootPath() ? rootPath() : undefined),
    (path) => listGithubWork({ rootPath: path }),
  );

  const filteredWork = (): GithubWorkItem[] => {
    const r = work();
    if (!r?.ok) return [];
    const q = filter().trim().toLowerCase();
    if (!q) return r.items;
    return r.items.filter(
      (it) => it.title.toLowerCase().includes(q) || String(it.number).includes(q),
    );
  };

  const { busy, error, submit } = useSubmit<void>(async () => {
    const repository = props.repository;
    if (source() === "prompt") {
      // Prompt is optional — empty just creates an empty workspace.
      await actions.createWorkspaceFromPromptMessage({ repository, prompt: prompt().trim() });
    } else if (source() === "branch") {
      await actions.createWorkspace({
        repository,
        name: wsName().trim(),
        branch: wsBranch().trim(),
        baseRef: wsBase().trim() || undefined
      });
    } else if (source() === "linear") {
      const issue = linearIssue().trim();
      if (!issue) throw new Error("Enter a Linear issue ID (e.g. ENG-123)");
      await actions.createWorkspaceFromLinear({ repository, issueId: issue });
    } else {
      const item = selected();
      if (!item) throw new Error("Select an issue or pull request");
      if (item.kind === "issue") {
        await actions.createWorkspaceFromIssue({ repository, issueNumber: item.number });
      } else {
        await actions.createWorkspaceFromPullRequest({ repository, prNumber: item.number });
      }
    }
  }, props.onDone);

  const sourceMeta: Record<Source, { label: string; detail: string }> = {
    prompt: {
      label: "Prompt",
      detail: "Start from a task brief and let the agent shape the workspace."
    },
    branch: {
      label: "Branch",
      detail: "Create a named workspace from a base branch."
    },
    github: {
      label: "GitHub",
      detail: "Start from an open issue or pull request using local gh auth."
    },
    linear: {
      label: "Linear",
      detail: "Start from a Linear issue when LINEAR_API_KEY is available."
    }
  };

  const sourceState = (key: Source) => {
    if (key === "github") {
      if (!rootPath()) return "No project path";
      if (work.loading) return "Loading";
      // The probe only runs once this tab is selected, so before then we know
      // nothing — `gh` may be signed in while this repo has no GitHub remote
      // at all. Saying "Ready" on an unrun check is a promise we cannot keep.
      const probe = work();
      if (probe === undefined) return "Not checked";
      if (probe.ok === false) return "Needs gh";
      return "Ready";
    }
    if (key === "linear") return "Needs key";
    return "Ready";
  };

  const missingRequirement = () => {
    if (source() === "github" && !selected()) return "Select a GitHub issue or pull request.";
    if (source() === "linear" && !linearIssue().trim()) return "Enter a Linear issue ID.";
    return "";
  };
  const canSubmit = () => !busy() && !missingRequirement();
  const previewRows = (): [string, string][] => {
    if (source() === "prompt") {
      return [
        ["Source", "Prompt"],
        ["Workspace", "Generated automatically"],
        ["First message", prompt().trim() ? "Prompt will be sent to the agent" : "No first message"],
      ];
    }
    if (source() === "branch") {
      return [
        ["Source", "Branch"],
        ["Workspace", wsName().trim() || "Generated automatically"],
        ["Branch", wsBranch().trim() || "Generated automatically"],
        ["Base", wsBase().trim() || "Repository default branch"],
      ];
    }
    if (source() === "linear") {
      return [
        ["Source", "Linear"],
        ["Issue", linearIssue().trim() || "Required"],
        ["Auth", "Requires LINEAR_API_KEY in archcar environment"],
      ];
    }
    const item = selected();
    return [
      ["Source", "GitHub"],
      ["Selection", item ? `${item.kind === "pr" ? "PR" : "Issue"} #${item.number}` : "Required"],
      ["Auth", "Uses local gh authentication"],
    ];
  };

  const submitLabel = () =>
    busy()
      ? "Creating..."
      : source() === "prompt"
        ? "Start workspace"
        : source() === "github"
          ? "Create from selection"
          : "Create workspace";

  const submitTitle = () => missingRequirement() || submitLabel();

  const sourceClass = (key: Source) => ({
    "dialog-source-active": source() === key,
    "dialog-source-warning": sourceState(key).startsWith("Needs")
  });

  const sourceTone = (key: Source) =>
    sourceState(key) === "Ready" ? "dialog-source-state-ready" : "dialog-source-state-action";

  const sourceItems: { key: Source; label: string; detail: string }[] = [
    { key: "prompt", ...sourceMeta.prompt },
    { key: "branch", ...sourceMeta.branch },
    { key: "github", ...sourceMeta.github },
    { key: "linear", ...sourceMeta.linear },
  ];

  return (
    <div class="dialog-form">
      <div class="dialog-source-grid">
        <For each={sourceItems}>
          {(s) => (
            <button
              class="dialog-source-card"
              classList={sourceClass(s.key)}
              onClick={() => setSource(s.key)}
            >
              <span class="dialog-source-card-head">
                <span class="dialog-source-label">{s.label}</span>
                <span class={`dialog-source-state ${sourceTone(s.key)}`}>
                  {sourceState(s.key)}
                </span>
              </span>
              <span class="dialog-source-detail">{s.detail}</span>
            </button>
          )}
        </For>
      </div>

      <Switch>
        <Match when={source() === "prompt"}>
          <label class="dialog-field"><span>Prompt</span>
            <textarea
              rows={4}
              value={prompt()}
              onInput={(e) => setPrompt(e.currentTarget.value)}
              placeholder="Describe the task… (optional — sent as the first message)"
            /></label>
          <span class="dialog-hint">Optional. Workspace + branch are named automatically; a prompt is sent as the first message and the agent renames from its reply.</span>
        </Match>
        <Match when={source() === "branch"}>
          <label class="dialog-field"><span>Workspace name</span>
            <input value={wsName()} onInput={(e) => setWsName(e.currentTarget.value)} placeholder="e.g. auth-refactor" /></label>
          <label class="dialog-field"><span>Branch name</span>
            <input value={wsBranch()} onInput={(e) => setWsBranch(e.currentTarget.value)} placeholder="e.g. lc/auth-refactor" /></label>
          <label class="dialog-field"><span>Base branch</span>
            <input
              value={wsBase()}
              onInput={(e) => setWsBase(e.currentTarget.value)}
              list="create-ws-base-branches"
              placeholder="Optional — defaults to the repo default branch"
            />
            <datalist id="create-ws-base-branches">
              <For each={baseBranches() ?? []}>{(b) => <option value={b} />}</For>
            </datalist>
          </label>
          <span class="dialog-hint">Creates a workspace on a new branch off the base. Leave name/branch blank to auto-generate.</span>
        </Match>
        <Match when={source() === "linear"}>
          <label class="dialog-field"><span>Linear issue ID</span>
            <input value={linearIssue()} onInput={(e) => setLinearIssue(e.currentTarget.value)} placeholder="e.g. ENG-123" /></label>
          <span class="dialog-hint">Creates a workspace from a Linear issue. Requires LINEAR_API_KEY in the daemon's environment.</span>
        </Match>
        <Match when={source() === "github"}>
          <div class="dialog-field">
            <div class="dialog-field-head">
              <span>Open issues &amp; pull requests</span>
              <button
                class="ui-button-icon"
                title="Reload"
                disabled={work.loading}
                onClick={() => void refetchWork()}
              >
                ⟳
              </button>
            </div>
            <Show
              when={work()?.ok}
              fallback={
                <Show
                  when={work.loading}
                  fallback={
                    <div class="dialog-error">
                      {work()?.ok === false ? (work() as { error: string }).error : "Could not load issues/PRs. Is gh installed & authed?"}
                    </div>
                  }
                >
                  <div class="dialog-hint">Loading issues &amp; PRs…</div>
                </Show>
              }
            >
              <input
                class="repo-search"
                value={filter()}
                onInput={(e) => setFilter(e.currentTarget.value)}
                placeholder="Search by title or number…"
              />
              <div class="repo-picker">
                <For each={filteredWork()} fallback={<div class="repo-empty">No open issues or PRs</div>}>
                  {(item) => {
                    const isSel = () =>
                      selected()?.kind === item.kind && selected()?.number === item.number;
                    return (
                      <button
                        type="button"
                        class="repo-card"
                        classList={{ selected: isSel() }}
                        onClick={() => setSelected(isSel() ? null : item)}
                      >
                        <div class="repo-card-text">
                          <span class="repo-card-title">
                            {item.kind === "pr" ? "PR" : "Issue"} #{item.number} · {item.title}
                          </span>
                          <span class="repo-card-sub">
                            {item.author ? `${item.author} · ` : ""}updated {relTime(item.updatedAt)}
                          </span>
                        </div>
                        <span class="repo-card-action">{isSel() ? "Selected" : "Select"}</span>
                      </button>
                    );
                  }}
                </For>
              </div>
            </Show>
          </div>
        </Match>
      </Switch>

      <div class="dialog-preview">
        <div class="dialog-preview-title">Workspace preview</div>
        <For each={previewRows()}>
          {([label, value]) => (
            <div class="dialog-preview-row">
              <span class="dialog-preview-label">{label}</span>
              <span class="dialog-preview-value">{value}</span>
            </div>
          )}
        </For>
      </div>

      <Show when={error()}>{(msg) => <div class="dialog-error">{msg()}</div>}</Show>
      <Show when={missingRequirement()}>{(msg) => <div class="dialog-hint">{msg()}</div>}</Show>
      <div class="dialog-actions">
        <button class="ui-button" onClick={props.onDone}>Cancel</button>
        <button
          class="ui-button-primary"
          disabled={!canSubmit()}
          title={submitTitle()}
          onClick={() => submit()}
        >
          {submitLabel()}
        </button>
      </div>
    </div>
  );
}
